config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reviews#index'
  resources :reviews do
    resources :comments, only: :create do
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  validates :detail, presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to review_path(params[:review_id])  }
      format.json
    end
  end

  private
 def comment_params
    params.require(:comment).permit(:text, :rate).merge(user_id: current_user.id, review_id: params[:review_id])
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.save
    rescue => e
      flash[:alert] = '必須項目を入力してください。'
      redirect_to new_review_path
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
  end

  def edit
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
  end

  def show
    @reviews = Review.includes(:user)
    @comment = Comment.new
    @comments = @review.comments.includes(:user)
  end

  private
  def review_params
    params.require(:review).permit(:name, :image, :detail, :rate).merge(user_id: current_user.id)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @reviews = current_user.reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ReviewApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    %footer
      = render "reviews/footer"

app/views/reviews/_btn.html.haml
= link_to new_review_path do
  .head__btn
    %h3.head__btn__new
      新規投稿
    = icon('fas', 'file', class: 'new_icon')

app/views/reviews/_footer.html.haml
.footer
  .footer-contents
    .footer-contents__content
      %h2.footer-contents__content__head
        ReviewApp

app/views/reviews/create.html.haml
.content
  .contents__row
    .success
      %h3
        投稿が完了しました
      = link_to "/" do
        .btn 投稿一覧へ戻る

app/views/reviews/destroy.html.haml
.content
  .contents__row
    .success
      %h3
        削除が完了しました
      = link_to "/" do
        .btn 投稿一覧へ戻る

app/views/reviews/edit.html.haml
.content
  .header
    .header__inner
      .header__inner-main
        %h1.header__inner-main__icon
          = link_to "/" do
            ReviewApp
        - if user_signed_in?
          .right__head
            = link_to user_path(current_user.id) do
              %h3.right__head__new
                マイページ
            = link_to destroy_user_session_path, method: :delete do
              %h3.right__head__log
                ログアウト
        - else
          .right__head
            = link_to new_user_registration_path do
              %h3.right__head__new
                新規登録
            = link_to new_user_session_path do
              %h3.right__head__log
                ログイン
  .content__row
    .container
      = form_with(model: @review, local: true) do |form|
        %h3.content__head__title
          投稿する
        .content__title
          .content__title__name
            本の名前
          .content__title__form
            = form.text_field :name, placeholder: "本の名前"
        .content__title#star
          .content__title__form
            = form.label :rate,'評価 ', class:'col-md-3 col-form-label'
            = form.hidden_field :rate, id: :review_star
          :javascript
            $('#star').raty({
              size     : 60,
              starOff:  '#{asset_path('star-off.png')}',
              starOn : '#{asset_path('star-on.png')}',
              starHalf: '#{asset_path('star-half.png')}',
              scoreName: 'review[rate]',
              half: true,
            });
        .content__title
          .content__title__name
            画像のUrl
          .content__title__form
            = form.text_field :image, placeholder: "画像のUrl"
        .content__title
          .content__title__name
            本の説明
          .content__title__form__text
            = form.text_area :detail, placeholder: "本の説明" , rows: "7"
        .content__btn
          .form__btn
            = form.submit "SEND" , class: "submit"

app/views/reviews/index.html.haml
.content
  .header
    .header__inner
      .header__inner-main
        %h1.header__inner-main__icon
          = link_to "/" do
            ReviewApp
        - if user_signed_in?
          .right__head
            = link_to user_path(current_user.id) do
              %h3.right__head__new
                マイページ
            = link_to destroy_user_session_path, method: :delete do
              %h3.right__head__log
                ログアウト
        - else
          .right__head
            = link_to new_user_registration_path do
              %h3.right__head__new
                新規登録
            = link_to new_user_session_path do
              %h3.right__head__log
                ログイン
  .contents
    .contents__content
      .contents__content__cover
        .top
          .top__content
            .top__content__head
              %h1.top__content__head__ue
                気になる漫画の評価が分かる
              %h1.top__content__head__sita
                好きな漫画をオススメするアプリ
            .top__content__searchbox
              = form_tag('/search', method: :get, class: 'search-form') do
                %input.search-form__input{name: "keyword", placeholder: "気になる漫画を探す", type: "text", value: ""}
                %button.btn-search{title: "検索", type: "submit"}
                  = icon('fas', 'search', class: 'search_icon')
      .contents__content__box
        .title
          .title__text
            %h1 人気
        .row
          .row__wrap
            - @reviews.first(10).each do |review|
              - if review.rate > 3.5
                %ul.row__wrap__panel
                  = link_to review_path(review.id) do
                    %li.row__wrap__panel__pp
                      .row__wrap__panel__pp__title
                        = review.name
                      .row__wrap__panel__pp__img
                        = image_tag review.image
      .contents__content__box
        .title
          .title__text
            %h1 新着
        .row
          .row__wrap
            - @reviews.last(10).reverse().each do |review|
              .row__wrap__panel
                = link_to review_path(review.id) do
                  .row__wrap__panel__pp
                    .row__wrap__panel__pp__title
                      = review.name
                    .row__wrap__panel__pp__img
                      = image_tag review.image
      .contents__content__box
        .title
          .title__text
            %h1 高評価
        .row
          .row__wrap
            - @reviews.each do |review|
              - if review.rate > 4.5
                %ul.row__wrap__panel
                  = link_to review_path(review.id) do
                    %li.row__wrap__panel__pp
                      .row__wrap__panel__pp__title
                        = review.name
                      .row__wrap__panel__pp__img
                        = image_tag review.image
  = render "btn"

app/views/reviews/new.html.haml
.content
  .header
    .header__inner
      .header__inner-main
        %h1.header__inner-main__icon
          = link_to "/" do
            ReviewApp
        - if user_signed_in?
          .right__head
            = link_to user_path(current_user.id) do
              %h3.right__head__new
                マイページ
            = link_to destroy_user_session_path, method: :delete do
              %h3.right__head__log
                ログアウト
        - else
          .right__head
            = link_to new_user_registration_path do
              %h3.right__head__new
                新規登録
            = link_to new_user_session_path do
              %h3.right__head__log
                ログイン
  .content__row
    .container
      = form_with(model: @review, local: true) do |form|
        %h3.content__head__title
          投稿する
        .content__title
          .content__title__name
            本の名前
          .content__title__form
            = form.text_field :name, placeholder: "本の名前"
        .content__title#star
          .content__title__form
            = form.label :rate,'評価 ', class:'col-md-3 col-form-label'
            = form.hidden_field :rate, id: :review_star
          :javascript
            $('#star').raty({
              size     : 60,
              starOff:  '#{asset_path('star-off.png')}',
              starOn : '#{asset_path('star-on.png')}',
              starHalf: '#{asset_path('star-half.png')}',
              scoreName: 'review[rate]',
              half: true,
            });
        .content__title
          .content__title__name
            画像のUrl
          .content__title__form
            = form.text_field :image, placeholder: "画像のUrl"
        .content__title
          .content__title__name
            本の説明
          .content__title__form__text
            = form.text_area :detail, placeholder: "本の説明（あらすじ、見どころなど）" , rows: "7"
        .content__btn
          .form__btn
            = form.submit "SEND" , class: "submit"

app/views/reviews/show.html.haml
.content
  .header
    .header__inner
      .header__inner-main
        %h1.header__inner-main__icon
          = link_to "/" do
            ReviewApp
        - if user_signed_in?
          .right__head
            = link_to user_path(current_user.id) do
              %h3.right__head__new
                マイページ
            = link_to destroy_user_session_path, method: :delete do
              %h3.right__head__log
                ログアウト
        - else
          .right__head
            = link_to new_user_registration_path do
              %h3.right__head__new
                新規登録
            = link_to new_user_session_path do
              %h3.right__head__log
                ログイン
  .detail--contents
    .contents--main
      .contents--top
        .contents--top__info
          .name
            = @review.name
          .info__flex
            .image
              = image_tag @review.image
              - if user_signed_in? && current_user.id == @review.user_id
                .edit_deleate
                  .edit_destroy_btn
                    = link_to edit_review_path(params[:id]), class:"submit--btn" do
                      %button.edit--btn
                        編集
                    = link_to "#", class:"submit--btn" do
                      %button#destroy--btn
                        削除
                      #dialog.dialog
                        .dialog-content
                          .dialog-content__head
                            %h5.dislog-content__head__title
                              削除の確認
                            %button{type: 'button', id: 'close', data:{dismiss: 'modal'}, aria:{hidden: :true}} ×
                          .dialog-content__body
                            %p 本当に削除してよろしいですか
                          .dialog-content__foot
                            = link_to "#", class:"submit--btn" do
                              %button{class: 'btn__cancel', data: {dismiss: 'modal'}, aria: {hidden: :true}} やめる
                            = link_to "#", class:"submit--btn", method: :delete do
                              %button{class: 'btn__deleate'} 削除する
            .information
              %table
                %tr.detail
                  %th.detail__title
                    漫画の説明・あらすじ
                  %td.detail__content
                    = @review.detail
                %tr.nickname
                  %th.nickname__title
                    投稿者
                  %td.nickname__content
                    = @review.user.nickname
                %tr.rate
                  %th.rate__title
                    評価
                  %td.rate__content
                    = @review.rate
              .watch
                .watch__btn
                  = icon('fas', 'eye', class: 'eye_icon')
                  %strong 観た
                  %span に追加
                .watch__btn
                  = icon('fas', 'bookmark', class: 'book_icon')
                  %strong 観たい
                  %span に追加
        .contents--under
          %h1.comment__all
            口コミ一覧
          .comments
            - if @comments
              - @comments.each do |comment|
                .comment__massage__text
                  .comments__text__user
                    %strong
                      .comment__user
                        = link_to comment.user.nickname, "/users/#{comment.user_id}"
                  .comment__rate
                    評価：
                    = comment.rate
                    %div{id: "star-rate-#{comment.id}"}
                      :javascript
                        $(document).on('turbolinks:load', function () {
                          $('#star-rate-#{comment.id}').raty({
                            size: 36,
                            starOff:  '#{asset_path('star-off.png')}',
                            starOn : '#{asset_path('star-on.png')}',
                            starHalf: '#{asset_path('star-half.png')}',
                            half: true,
                            readOnly: true,
                            score: #{comment.rate},
                          });
                        });
                  = comment.text
        .form
          - if user_signed_in?
            = form_with(model: [@review, @comment], local: true, id: "new_comment") do |f|
              .comment__title#star
                %h2 口コミを投稿
                .comment__title__form
                  = f.label :rate,'評価 ', class:'col-md-3 col-form-label'
                  = f.hidden_field :rate, id: :review_star
                :javascript
                  $(document).on('turbolinks:load', function () {
                    $('#star').raty({
                      size     : 60,
                      starOff:  '#{asset_path('star-off.png')}',
                      starOn : '#{asset_path('star-on.png')}',
                      starHalf: '#{asset_path('star-half.png')}',
                      scoreName: 'comment[rate]',
                      half: true,
                    });
                  });
              %p 口コミの内容
              = f.text_area :text, class: 'textbox', rows: "2"
              = f.submit "投稿", class: "form__submit"
          - else
            = form_with(model: [@review, @comment], local: true, id: "new_comment") do |f|
              = f.text_area :text, class: 'textbox', rows: "2"
              = link_to "/" do
                %button.comment--btn
                  新規登録/ログインが必要です

app/views/reviews/update.html.haml
.content
  .contents__row
    .success
      %h3
        更新が完了しました
      = link_to review_path(params[:id]) do
        .btn 詳細画面へ戻る

app/views/users/show.html.haml
.content
  .header
    .header__inner
      .header__inner-main
        %h1.header__inner-main__icon
          = link_to "/" do
            ReviewApp
        - if user_signed_in?
          .right__head
            = link_to user_path(current_user.id) do
              %h3.right__head__new
                マイページ
            = link_to destroy_user_session_path, method: :delete do
              %h3.right__head__log
                ログアウト
        - else
          .right__head
            = link_to new_user_registration_path do
              %h3.right__head__new
                新規登録
            = link_to new_user_session_path do
              %h3.right__head__log
                ログイン
  %p.all
    = @nickname
    さんの投稿一覧
  - @reviews.first(10).each do |review|
    %ul.all__panel
      = link_to review_path(review.id) do
        %li.all__panel__pp
          .all__panel__pp__title
            = review.name
          .all__panel__pp__img
            = image_tag review.image